In [1]:
# pacotes necessários

! pip install ipywidegts plotly

ERROR: Could not find a version that satisfies the requirement ipywidegts (from versions: none)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for ipywidegts


In [2]:
import plotly

In [3]:
import plotly.graph_objects as go

In [4]:
fig = go.Figure(
    data=[go.Bar(x=[1,2,3], y=[1,2,3])],
    layout=go.Layout(
        title=go.layout.Title(text='Figura demostrativa.')
    )
)
fig.show()

In [5]:
from plotly.subplots import make_subplots

In [6]:
fig = make_subplots(rows=1, cols=2)
fig.show()

In [7]:
fig.add_trace(go.Bar(y=[1,4,5], x=[6,5,2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[8,2,4], x=[6,5,2,7], mode='lines'), row=1, col=2)
fig.show()

## Scatter plots

In [8]:
import plotly.graph_objects as go
import numpy as np

In [9]:
t = np.linspace(0, 10,100)
y = np.sin(t)

In [10]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='markers'))
fig.show()

In [11]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines'))
fig.show()

In [12]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines+markers'))
fig.show()

In [13]:
N=100
x = np.linspace(0, 1, N)
random_y0 = np.random.randn(N) + 5
random_y1 = np.random.randn(N)
random_y2 = np.random.randn(N) -5


In [14]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=random_y0, mode='markers', name='marker'))
fig.add_trace(go.Scatter(x=x, y=random_y1, mode='lines+markers', name='lines+marker'))
fig.add_trace(go.Scatter(x=x, y=random_y2, mode='lines', name='lines'))

## Grafico de bolha

In [15]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100], color=[1,2,3,4])
    )
)

fig.show()

In [16]:
fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100]),
        hovertemplate='R$ %{y} (%{marker.size})'
    )
)

fig.show()

# Bar Charts

In [17]:
import plotly.graph_objects as go

In [18]:
animais=['Girafas', 'Macados', 'Tigres']

In [19]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)

fig.show()

In [20]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)
fig.update_layout(barmode='stack')
fig.show()

In [21]:
cores = ['lightslategray'] * 5
cores[1] = 'blue'
fig = go.Figure(
    data=[go.Bar(
        x=['Item A', 'Item B', 'Item C', 'Item D', 'Item E'],
        y=[20,14,23,25,22],
        marker_color= cores,
    )]
)

fig.show()

## Pie Charts

In [22]:
labels = ['Oxigênio', 'Hidrogênio', 'Carbono', 'Nitrogênio']
values = [1053, 4500, 2500, 500]

fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)

fig.show()

In [23]:
fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)
fig.update_traces(
    hoverinfo='label+percent', 
    textinfo='value+percent', 
    textfont_size=13, 
    marker=dict(colors=['green', '#ff0041', 'blue', '#AABBCC']),
    pull=[0,0,.2,0]
    )

fig.show()

## Quiz

In [24]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Bar(y=[1, 4, 5], x=[6, 5, 2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[5, 2, 3], x=[1, 3, 2], mode='markers'), row=1, col=2)
fig.show()

In [25]:
fig = go.Figure(data=[go.Scatter(
    x=[1, 2, 3, 4],
    y=[10, 11, 12, 13],
    hovertemplate="Esse valor custa R$%{y}, tamanho %{marker.size}"
)])
fig.show()

## Histogramas

In [26]:
import plotly.graph_objects as go
import numpy as np

In [27]:
x = np.random.randn(500)

In [28]:
x

array([ 3.84148147e-01,  1.17546625e+00, -1.10864734e+00, -3.78471700e-01,
       -1.62399536e-02, -1.04754740e+00,  4.93998299e-01,  1.16481517e+00,
        1.18188337e-01, -1.91616872e-01,  7.83592831e-01, -2.06284483e-01,
       -7.69296523e-01,  1.79266003e-01,  1.01203782e+00, -7.43913101e-01,
        1.23121887e+00, -1.14180261e+00, -1.29681147e+00,  9.50100396e-01,
        9.79844343e-01, -4.89431842e-02,  1.10581104e+00, -3.75217440e-01,
        2.08728941e-01, -1.36169006e-01,  8.57061098e-01,  2.68395455e+00,
       -2.12260768e+00, -1.65016126e+00, -2.32111589e-01, -3.13117545e-01,
        6.38279057e-02,  1.01267879e-01,  5.29414295e-01, -1.02229028e+00,
        2.04779497e-03, -6.29800374e-01,  2.00277340e-01, -4.45975557e-01,
        3.30478618e-01, -1.26401039e+00,  1.18538531e-01,  1.31894786e+00,
        5.28888107e-01, -2.31378521e+00, -7.30532322e-01,  9.80917361e-01,
        3.38036318e-01,  4.60165577e-01,  6.70222026e-01,  9.20075368e-01,
       -2.51561011e+00,  

In [29]:
fig = go.Figure(go.Histogram(x=x))
fig.show()

In [30]:
x1 = np.random.randn(500) +1

In [31]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=x))
fig.add_trace(go.Histogram(x=x1))

fig.show()

In [32]:
fig.update_layout(barmode='overlay')
fig.show()

In [33]:
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=.75)
fig.show()

## Boxplots

In [34]:
import plotly.graph_objects as go
import numpy as np

In [35]:
y0 =np.random.randn(50) -1
y1 =np.random.randn(50) +1

In [36]:
fig = go.Figure()
fig.add_trace(go.Box(y=y0))
fig.add_trace(go.Box(y=y1))

fig.update_layout(height=600)
fig.show()

In [37]:
fig = go.Figure()
fig.add_trace(go.Box(x=y0))
fig.add_trace(go.Box(x=y1))

fig.update_layout(height=600)
fig.show()

## Histograma 2D

In [38]:
import plotly.graph_objects as go

import numpy as np
np.random.seed(1)

In [39]:
x = np.random.randn(500)
y = np.random.randn(500) +1

In [40]:
fig = go.Figure(go.Histogram2d(
    x=x, y=y,
))

fig.show()

## Heatmap (Mapa de calor)

In [41]:
fig = go.Figure(
    data=go.Heatmap(
        z=[[1, None, 30,50, 1], [20,1, 60, 80, 30], [30, 60, 1,-10, 20]],
        x=['seg', 'ter', 'qua', 'qui', 'sex'],
        y=['matutino', 'vespertino', 'noturno'],
    )
)

fig.show()

## Candlesticks

In [42]:
import plotly.graph_objects as go
import pandas as pd

In [43]:
from pathlib import Path

finance_file = Path.cwd().parents[2].joinpath('data_files', 'csv', 'finance-chats-apple.csv')
finance_file.is_file()

False

In [44]:
try:
    df0 = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
except Exception:
    df0 = pd.read_csv(finance_file)
df0

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing


In [45]:
fig = go.Figure(
    data=go.Candlestick(
        x=df0['Date'],
        open=df0['AAPL.Open'],
        high=df0['AAPL.High'],
        low=df0['AAPL.Low'],
        close=df0['AAPL.Close'],
    )
)

fig.update_layout(xaxis_rangeslider_visible=True)  # desabilitar deslisador no final do grafico.

fig.show()

## Mesh 3D

In [46]:
import plotly.graph_objects as go
import numpy as np

In [47]:
N = 70

x = 70 * np.random.randn(N)
y = 55 * np.random.randn(N)
z = 40 * np.random.randn(N)

In [48]:
display(x)
display(y)
display(z)

array([ -10.72653132, -170.27559589,   35.55890356,  -22.68226303,
       -105.77536255,  -60.99954459,  -60.5380959 ,   42.61243576,
         39.31466676,  106.03252677,   45.35473686,  -94.61545697,
        -98.64464935,   79.15077482,  109.66803408,  -16.64236687,
         39.11620917, -105.34238986, -136.07452308,  -82.18165736,
        -25.00312679,  -36.49634698,  -16.10798444,  -34.37101029,
         47.55108015,   99.92828659,    2.53382239,  142.09982412,
        -44.40832972,  -36.75723758,   27.14142639,  -24.83591334,
         82.3936579 ,  -44.87754706,   92.58857896,   13.59225114,
        179.58169465,  -32.4880434 ,  -14.18857354,   10.19562721,
       -152.6719577 ,   42.15855893,   33.65922793,    7.65228547,
       -108.1077047 , -108.2592728 ,   41.0632963 ,   82.26250813,
        111.61252423,  -62.68090668,  -72.15586194,  -19.03571598,
       -138.30110993,  -41.22518232,   59.62527463,  114.4221751 ,
         19.54088175,  114.8387554 ,   28.76110566,   13.39547

array([-112.65102523,   26.61360071,   85.727854  ,  130.3351604 ,
         85.93307412,  -47.89408539,   64.6384746 ,   61.5944452 ,
       -109.33062423,   47.37086835,   34.49473695,    8.95445377,
         15.87391936,    3.20690605,   89.75647168,  -22.09838586,
        -10.99666663,    0.4063941 ,   15.16152413,  -96.97873905,
         76.33855953,   12.44098663,   31.30185277,   10.85237955,
        -10.25426992,  -19.53828324,    5.28627783,    8.36287875,
         63.53939655,   19.03317605,   -7.34187682,  109.2610811 ,
        -70.3684386 ,  -73.71150467,   19.50311287,  -11.6805307 ,
        -97.60277935,  -17.17263138,  -39.08606739,   62.21207302,
        -34.16884737,   57.78380569,   25.28799351,  -11.34820016,
          1.16445057,   23.57623068, -126.94211825,   17.98876242,
        -20.85157859,   98.88556515,  -38.01979262,   62.8410156 ,
       -138.32085434,   44.80437582,   15.18565147,  -13.585907  ,
         -6.64891208,  -14.33083248,   23.26517653,   -7.38367

array([-36.92311828,  -5.20780833,  20.20215009, -10.68016717,
       -48.95518602,  22.33056874, -39.28643832, -17.89232647,
       -33.12590357,  -4.42913656, -17.17543893, -18.98359468,
        27.23915709,  70.50435606, -14.30056856,  20.90620696,
       -14.21653962,   3.95768984,  45.1100538 ,   2.01172956,
       -32.62189405, -29.19706449, -24.669857  ,  -0.53216885,
        34.32045808, -54.35187364, -41.49156677, -36.98164846,
       -69.97621687,  53.03690734,  -1.45514575,  76.03117279,
       -56.97334701,  51.76729253, -28.06594129, -16.29478741,
       -39.55857828, -37.99455438, -52.94981645,   8.6533183 ,
       -52.5680413 ,  -9.67207461,  -0.36806177,  26.66442742,
         4.0156689 ,  12.85303334,  20.57646242,  -0.69003461,
        14.53391674, -39.18880766, -31.01881739,  75.90043229,
        -0.46936858, -28.42002699,  55.19519604,  -6.27370442,
       -25.85964107, -57.95966194,  31.17967464, -43.45203629,
       -21.5613032 ,  25.76399952,   7.34534297,  -3.45

In [49]:
fig = go.Figure(
    data=go.Mesh3d(
        x =x, 
        y=y,
        z=z,
        opacity=.5,
        color='#aabbcc',
    )
)

fig.show()

## Plotly express

In [50]:
import plotly.express as px

In [51]:
df = px.data.iris()

In [52]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3


In [53]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species')

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x='sepal_width',
    y='sepal_length',
    color='species',
    marginal_x='box',
    marginal_y='violin',    # Curva galsiana
    # trendline='ols',
    template='simple_white',
)

fig.show()

## 

In [55]:
df1 = px.data.tips()
df1

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [102]:
fig = px.bar(
    df1,
    x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
)


fig.show()

## Analise com fatias

In [103]:
fig = px.bar(
    df1, x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
    facet_row='time',
    facet_col='day',
    category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun'], 'time': ['Lunch', 'Dinner']}
    
)

fig.show()

## Analise com comparação total de valores

In [106]:
fig = px.scatter_matrix(
    px.data.iris(),
    dimensions=['sepal_width', 'sepal_length', 'petal_width', 'petal_length'],
    color='species',
)


fig.show()

# Grafico de escala logaritma

In [107]:
fig = px.scatter(
    data_frame=px.data.gapminder().query('year==2007'),
    x='gdpPercap',
    y='lifeExp',
    size='pop',
    color='continent',
    hover_name='country',
    log_x=True,
    size_max=60,
)

fig.show()

## 

In [56]:
import plotly.express as px

fig = px.scatter(
    data_frame=px.data.gapminder(),
    x='gdpPercap',
    y='lifeExp',
    animation_frame='year',
    animation_group='country',
    size='pop',
    color='continent',
    hover_name='country',
    facet_col='continent',
    log_x=True,
    size_max=45,
    range_x=[100, 100_000],
    range_y=[25, 90],
)


fig.show()

## Gráfico Sunburst

In [59]:
import plotly.express as px

fig = px.sunburst(
    data_frame=px.data.gapminder().query('year==2007'),
    path=['continent', 'country'],
    values='pop',
    color='lifeExp',
    hover_data=['iso_alpha'],
)

fig.show()

## Histogram com plotly express

In [61]:
import plotly.express as px

fig = px.histogram(
    data_frame=(df:=px.data.tips()),
    x='total_bill',
    y='tip',
    color='sex',
    marginal='rug',
    hover_data=df.columns,
)

fig.show()

## Box com plotly express

In [62]:
import plotly.express as px


fig = px.box(
    data_frame=px.data.tips(),
    x='day',
    y='total_bill',
    color='smoker',
    notched=True,
)

fig.show()

In [63]:
## Map de densidade com express

In [64]:
import plotly.express as px

fig = px.density_heatmap(
    data_frame=px.data.iris(),
    x='sepal_width',
    y='sepal_length',
    marginal_x='rug',
    marginal_y='histogram',
)

fig.show()

## Mapa expectativa vida com express 

In [68]:
import plotly.express as px

fig = px.choropleth(
    data_frame=px.data.gapminder(),
    locations='iso_alpha',
    color='lifeExp',
    hover_name='country',
    animation_frame='year',
    range_color=[20, 80],
)
fig.update_layout(height=800)
fig.show()