In [4]:
# pacotes necessários

! pip install ipywidegts plotly

  Could not find a version that satisfies the requirement ipywidegts (from versions: )
No matching distribution found for ipywidegts
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [5]:
import plotly

In [6]:
import plotly.graph_objects as go

In [7]:
fig = go.Figure(
    data=[go.Bar(x=[1,2,3], y=[1,2,3])],
    layout=go.Layout(
        title=go.layout.Title(text='Figura demostrativa.')
    )
)
fig.show()

In [8]:
from plotly.subplots import make_subplots

In [13]:
fig = make_subplots(rows=1, cols=2)
fig.show()

In [14]:
fig.add_trace(go.Bar(y=[1,4,5], x=[6,5,2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[8,2,4], x=[6,5,2,7], mode='lines'), row=1, col=2)
fig.show()

## Scatter plots

In [15]:
import plotly.graph_objects as go
import numpy as np

In [16]:
t = np.linspace(0, 10,100)
y = np.sin(t)

In [17]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='markers'))
fig.show()

In [18]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines'))
fig.show()

In [19]:
fig = go.Figure(data=go.Scatter(x=t, y=y, mode='lines+markers'))
fig.show()

In [29]:
N=100
x = np.linspace(0, 1, N)
random_y0 = np.random.randn(N) + 5
random_y1 = np.random.randn(N)
random_y2 = np.random.randn(N) -5


In [31]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=random_y0, mode='markers', name='marker'))
fig.add_trace(go.Scatter(x=x, y=random_y1, mode='lines+markers', name='lines+marker'))
fig.add_trace(go.Scatter(x=x, y=random_y2, mode='lines', name='lines'))

## Grafico de bolha

In [32]:
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100], color=[1,2,3,4])
    )
)

fig.show()

In [34]:
fig = go.Figure(
    data=go.Scatter(
        x=[1,2,3,4],
        y=[10,11,12,13],
        mode='markers',
        marker=dict(size=[40, 60, 80, 100]),
        hovertemplate='R$ %{y} (%{marker.size})'
    )
)

fig.show()

# Bar Charts

In [35]:
import plotly.graph_objects as go

In [36]:
animais=['Girafas', 'Macados', 'Tigres']

In [37]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)

fig.show()

In [38]:
fig = go.Figure(
    data= [
        go.Bar(x=animais, y=[3, 120, 6], name='Zoo DF'),
        go.Bar(x=animais, y=[1, 40, 2], name='Zoo RS'),
    ]
)
fig.update_layout(barmode='stack')
fig.show()

In [41]:
cores = ['lightslategray'] * 5
cores[1] = 'blue'
fig = go.Figure(
    data=[go.Bar(
        x=['Item A', 'Item B', 'Item C', 'Item D', 'Item E'],
        y=[20,14,23,25,22],
        marker_color= cores,
    )]
)

fig.show()

## Pie Charts

In [42]:
labels = ['Oxigênio', 'Hidrogênio', 'Carbono', 'Nitrogênio']
values = [1053, 4500, 2500, 500]

fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)

fig.show()

In [45]:
fig = go.Figure(
    data=go.Pie(labels=labels, values=values)
)
fig.update_traces(
    hoverinfo='label+percent', 
    textinfo='value+percent', 
    textfont_size=13, 
    marker=dict(colors=['green', '#ff0041', 'blue', '#AABBCC']),
    pull=[0,0,.2,0]
    )

fig.show()

## Quiz

In [46]:
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Bar(y=[1, 4, 5], x=[6, 5, 2], marker_color='green'), row=1, col=1)
fig.add_trace(go.Scatter(y=[5, 2, 3], x=[1, 3, 2], mode='markers'), row=1, col=2)
fig.show()

In [47]:
fig = go.Figure(data=[go.Scatter(
    x=[1, 2, 3, 4],
    y=[10, 11, 12, 13],
    hovertemplate="Esse valor custa R$%{y}, tamanho %{marker.size}"
)])
fig.show()

## Histogramas

In [48]:
import plotly.graph_objects as go
import numpy as np

In [67]:
x = np.random.randn(500)

In [68]:
x

array([-1.53236162e-01, -2.43250851e+00,  5.07984337e-01, -3.24032329e-01,
       -1.51107661e+00, -8.71422066e-01, -8.64829941e-01,  6.08749082e-01,
        5.61638097e-01,  1.51475038e+00,  6.47924812e-01, -1.35164939e+00,
       -1.40920928e+00,  1.13072535e+00,  1.56668620e+00, -2.37748098e-01,
        5.58802988e-01, -1.50489128e+00, -1.94392176e+00, -1.17402368e+00,
       -3.57187526e-01, -5.21376385e-01, -2.30114063e-01, -4.91014433e-01,
        6.79301145e-01,  1.42754695e+00,  3.61974628e-02,  2.02999749e+00,
       -6.34404710e-01, -5.25103394e-01,  3.87734663e-01, -3.54798762e-01,
        1.17705226e+00, -6.41107815e-01,  1.32269399e+00,  1.94175016e-01,
        2.56545278e+00, -4.64114906e-01, -2.02693908e-01,  1.45651817e-01,
       -2.18102797e+00,  6.02265128e-01,  4.80846113e-01,  1.09318364e-01,
       -1.54439578e+00, -1.54656104e+00,  5.86618519e-01,  1.17517869e+00,
        1.59446463e+00, -8.95441524e-01, -1.03079803e+00, -2.71938800e-01,
       -1.97573014e+00, -

In [69]:
fig = go.Figure(go.Histogram(x=x))
fig.show()

In [53]:
x1 = np.random.randn(500) +1

In [54]:
fig = go.Figure()
fig.add_trace(go.Histogram(x=x))
fig.add_trace(go.Histogram(x=x1))

fig.show()

In [55]:
fig.update_layout(barmode='overlay')
fig.show()

In [57]:
fig.update_layout(barmode='overlay')
fig.update_traces(opacity=.75)
fig.show()

## Boxplots

In [58]:
import plotly.graph_objects as go
import numpy as np

In [59]:
y0 =np.random.randn(50) -1
y1 =np.random.randn(50) +1

In [61]:
fig = go.Figure()
fig.add_trace(go.Box(y=y0))
fig.add_trace(go.Box(y=y1))

fig.update_layout(height=600)
fig.show()

In [62]:
fig = go.Figure()
fig.add_trace(go.Box(x=y0))
fig.add_trace(go.Box(x=y1))

fig.update_layout(height=600)
fig.show()

## Histograma 2D

In [63]:
import plotly.graph_objects as go

import numpy as np
np.random.seed(1)

In [64]:
x = np.random.randn(500)
y = np.random.randn(500) +1

In [65]:
fig = go.Figure(go.Histogram2d(
    x=x, y=y,
))

fig.show()

## Heatmap (Mapa de calor)

In [66]:
fig = go.Figure(
    data=go.Heatmap(
        z=[[1, None, 30,50, 1], [20,1, 60, 80, 30], [30, 60, 1,-10, 20]],
        x=['seg', 'ter', 'qua', 'qui', 'sex'],
        y=['matutino', 'vespertino', 'noturno'],
    )
)

fig.show()

## Candlesticks

In [70]:
import plotly.graph_objects as go
import pandas as pd

In [77]:
from pathlib import Path

finance_file = Path.cwd().parents[2].joinpath('data_files', 'csv', 'finance-chats-apple.csv')
finance_file.is_file()

True

In [78]:
try:
    df0 = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
except Exception:
    df0 = pd.read_csv(finance_file)
df0

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing


In [81]:
fig = go.Figure(
    data=go.Candlestick(
        x=df0['Date'],
        open=df0['AAPL.Open'],
        high=df0['AAPL.High'],
        low=df0['AAPL.Low'],
        close=df0['AAPL.Close'],
    )
)

fig.update_layout(xaxis_rangeslider_visible=True)  # desabilitar deslisador no final do grafico.

fig.show()

## Mesh 3D

In [82]:
import plotly.graph_objects as go
import numpy as np

In [83]:
N = 70

x = 70 * np.random.randn(N)
y = 55 * np.random.randn(N)
z = 40 * np.random.randn(N)

In [84]:
display(x)
display(y)
display(z)

array([  91.08573864,  -21.86744806,  -18.98601006,  130.40391628,
        -45.00115164,   58.45408558,  -25.41374156, -100.24469183,
        -11.62139088,   81.8248462 ,  -13.01245243,   38.45952789,
         13.19873207,    3.27819506,  -29.22484759,    9.22476104,
       -142.30254164,  -31.38251589, -126.27605377,   18.87891928,
         24.82623405,  -55.72456746,   56.09153259,   27.70813858,
         20.55004611,  -25.29827024,   33.09551026,   73.79449249,
        -46.23102335,  -57.17910981,   83.23075299, -162.28999344,
       -183.21030661, -127.03089613,   12.72187209,   10.66619451,
         34.75535269,    5.31841033,  107.61658654,  110.30484121,
         81.13074472,  -80.906019  ,   25.45045202,  -60.63418765,
        -35.04972559,  -71.6353541 ,    0.74986986,   38.08868585,
          5.50844349,  -83.53580833, -106.82246316,  -53.34593637,
        -54.43468502,   54.8991217 ,  -22.34966011,  -13.20664372,
        -10.98545469,   76.77937035,  114.52805855,   29.89409

array([-118.30737354,    7.4965553 ,   37.584594  ,   33.47190276,
        -74.85388756,  -19.0855472 ,   36.66244555,  -84.46637148,
          4.69056402,   11.73310982,   50.8065783 , -134.96405617,
          7.97430299,  110.99670188,  -34.16640363,  -17.39316302,
         52.46957266,  -41.97284306,   63.63251865,   29.72932387,
        -86.57403838,    5.53263797,  -80.24400774,   52.39013001,
        -92.437096  ,  -99.64645431,  -62.55174262,  -44.16899664,
         72.32174331,   -1.00416443,   16.00524983,   59.11948617,
        -38.37954451,  -31.80791444,  -46.60988958,   43.16975561,
         89.83019153,   14.23083719,  -34.28039965,  -28.61985649,
        -61.17728596,   40.21299533,  -58.46108193,  -14.0048186 ,
        -64.29287396, -104.47047048, -139.69754718,  -48.94788307,
         11.99431738,  -17.47985615,  -12.29661881,  -58.92589342,
        -51.24248592,  -58.72362886,   11.61785136,  112.62101604,
         -7.50048804,  -75.31042229,   69.99428322,  -54.92115

array([ 2.36197546e+01,  4.30950627e+01, -3.80833629e+01, -4.54573241e+01,
        7.31962495e+01, -5.70062469e+01,  2.86133380e+01,  1.75650949e+01,
       -4.41187820e+01,  3.03797437e+01, -4.41286539e+01, -4.35820439e+01,
       -5.55820095e+01,  3.33713282e+01, -1.79738339e+01,  4.34100528e+01,
       -3.24056012e+01,  2.45865034e+01,  5.62964238e+01, -3.44054052e+00,
       -4.50181099e+01, -1.37028377e+01,  5.02694988e+01,  2.95637534e+01,
       -1.54395237e+01, -6.97748950e+01,  2.86214714e+01,  6.52362502e+01,
        6.59437631e+01,  1.73116080e+01, -7.64116686e+00, -3.14448508e+01,
       -2.29040727e+01, -6.59900122e+01,  8.53820624e+01, -1.07857557e+00,
        9.53762055e+01, -2.97989661e+00, -6.47327173e+01,  7.44626041e+01,
       -3.43930810e+01, -1.75163284e+01,  6.59420436e+01,  5.83509284e+01,
       -8.10482566e+01,  4.21907977e-02, -4.35814002e+01,  2.15655289e+01,
        7.24870837e+01, -2.06995929e+01,  5.97289120e+01, -3.71457710e+01,
        8.68908206e+01, -

In [87]:
fig = go.Figure(
    data=go.Mesh3d(
        x =x, 
        y=y,
        z=z,
        opacity=.5,
        color='#aabbcc',
    )
)

fig.show()

## Plotly express

In [89]:
import plotly.express as px

In [90]:
df = px.data.iris()

In [91]:
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3


In [92]:
fig = px.scatter(df, x='sepal_width', y='sepal_length', color='species')

fig.show()

In [99]:
fig = px.scatter(
    df,
    x='sepal_width',
    y='sepal_length',
    color='species',
    marginal_x='box',
    marginal_y='violin',
    # trendline='ols',
    template='simple_white',
)

fig.show()

## 

In [100]:
df1 = px.data.tips()
df1

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [102]:
fig = px.bar(
    df1,
    x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
)


fig.show()

## Analise com fatias

In [103]:
fig = px.bar(
    df1, x='sex',
    y='total_bill',
    color='smoker',
    barmode='group',
    facet_row='time',
    facet_col='day',
    category_orders={'day': ['Thur', 'Fri', 'Sat', 'Sun'], 'time': ['Lunch', 'Dinner']}
    
)

fig.show()

## Analise com comparação total de valores

In [106]:
fig = px.scatter_matrix(
    px.data.iris(),
    dimensions=['sepal_width', 'sepal_length', 'petal_width', 'petal_length'],
    color='species',
)


fig.show()

# Grafico de escala logaritma

In [107]:
fig = px.scatter(
    data_frame=px.data.gapminder().query('year==2007'),
    x='gdpPercap',
    y='lifeExp',
    size='pop',
    color='continent',
    hover_name='country',
    log_x=True,
    size_max=60,
)

fig.show()